### ISSUE TITLE
Trouble getting this to work

### ISSUE THREAD

**Issue by skinofstars** [westmark/sequelize-multi-tenant-enhancer#1]
Hey, I've been having trouble getting this to work.

I'm setting up as follows

```javascript
// setup
const enhancer = require('sequelize-multi-tenant-enhancer')
const db = {}
let sequelize = new Sequelize(DB_STRING)
db.Config = sequelize['import'](path.join(__dirname, 'config.js'))
db.sequelize = enhancer(sequelize)

// then try to use
db.sequelize.withSchema('barry')
db.Config.findOne()
// or
db.sequeliz.models.Config.findOne()
```

These both return `SELECT "id" FROM "Config" AS "Config";`, which is missing the schema. Any ideas appreciated.

**Comment by westmark** [comment]
Hey,

`withSchema()` returns a new proxied version of the sequelize connection. Use that instead. Like this

```
db.sequelize = enhancer(sequelize);
const sequelizeWithSchema = db.sequelize.withSchema('barry');
sequelizeWithSchema.models.Config.findOne()
```

**Comment by skinofstars** [comment]
After much searching, I've found my issue. I needed to set the dialect options in the Sequelize initialisation config to include searchPath.

```javascript
const sequelize = new Sequelize(DB_STRING, {
  dialectOptions: {
    prependSearchPath: true
  }
})
```

**Comment by westmark** [comment]
Thanks for adding your solution here. I'll make a note about it in the readme.
