### ISSUE TITLE
Multiple Schemas not working

### ISSUE THREAD

**Issue by msameerbm** [westmark/sequelize-multi-tenant-enhancer#2]
This is my api code:

```javascript
const Sequelize = require('sequelize');
const enhance = require('sequelize-multi-tenant-enhancer');
const Inventory = require('./models/inventory');

const db = new Sequelize('postgres://localhost:5432/test');

db.authenticate().then((err) => {
  if (err) {
    console.log('There is connection in ERROR.');
  } else {
    console.log('Postgres Connection has been established successfully');
  }
});
db.sync().then(() => {
  console.log('Missing Table Created');
}, (err) => {
  console.log('An error occurred while creating the table:', err.message);
});

db.define('inventory', Inventory);

const enhancedSeq = enhance(db);

// const clientA = enhancedSeq.withSchema('client-a');
const clientB = enhancedSeq.withSchema('client-b');


// apis
exports.getAllBusiness = (req, res) => {
  clientB.models.inventory.findAll()
    .then((results) => {
      res.send(results);
    });
};

exports.postBusiness = (req, res) => {
  const user = {
    name: 'sameer',
  };
  clientB.models.inventory.create(user)
    .then(data => res.status(200).send(data))
    .catch(Sequelize.ValidationError, err => res.status(422).send(err.errors[0].message))
    .catch(err => res.status(400).send(err.message));
};

```

My inventory model:
```javascript
const Sequelize = require('sequelize');

module.exports = {
  name: Sequelize.STRING,
  code: Sequelize.STRING,
  price: Sequelize.STRING,
};

```

I am using postgres as a database, Initially the tables are successfully created, after creation i am hitting my post api with clientA schema so now data successfully stored in my db, but if i change my findAll code with clientB, still the data shows up!

**Comment by westmark** [comment]
Hi @sameercodes. Sorry to inform you that I moved away from Sequelize and am not maintaining this lib any longer. 

However, I believe the problem is that you are running `sync()` using `db` when you should be using `clientA` and/or `clientB` - you have to sync once for every tenant. `db.sync()` causes the tables to be added to the public schema, which should explain why both client A and B can access them.

**Comment by msameerbm** [comment]
@westmark Thanks🙏

I tried this and make it worked! (But i make it worked without this library)

We are planning to build a SaaS based product, so mainly after a lot of search, we found there are three database approach for designing a SaaS product.

1. Separate database for each tenant
2. Separate schemas for each tenant
3. Shared schema and one databases for all tenants(But will query using tenant_id)

Finally i decided to use option 2, and i moved to Postgresql instead of mysql, because Postgresql has schema based approach!

Now my final code:

```javascript
const postgresDB = new Sequelize('postgres://localhost:5432/test_enduser');

postgresDB.authenticate().then((err) => {
  if (err) {
    console.log('There is connection in ERROR.');
  } else {
    console.log('Postgres Connection has been established successfully');
  }
});

postgresDB.define('inventory', {
  name: Sequelize.STRING,
});

const createSchema = () => {
  Business.findAll({
    raw: true,
  }).then((data) => {
    data.forEach((client) => {
      postgresDB.createSchema(client.code).then(() => {
        Object.keys(postgresDB.models).forEach((currentItem) => {
          postgresDB.models[currentItem].schema(client.code).sync();
        });
        // new schema is created
        console.log('Postgres schema created');
      }).catch((err) => {
        console.log(err.message);
      });
    });
  });
};
createSchema();


// apis
exports.getAllBusiness = (req, res) => {
  postgresDB.models.inventory.schema(req.user.code).findAll()
    .then((results) => {
      res.send(results);
    });
};

exports.postBusiness = (req, res) => {
  const user = {
    name: req.body.name,
  };
  postgresDB.models.inventory.schema(req.user.code).create(user)
    .then(data => res.status(200).send(data))
    .catch(Sequelize.ValidationError, err => res.status(422).send(err.errors[0].message))
    .catch(err => res.status(400).send(err.message));
};
```


I am setting my postgres connection

Simply for test i am creating a table called "inventory"

In my application a online came and he signup, while signup i am storing there Business Code into my Business table(The Business table coming from separate DB, which is a super main app DB), so i am finding the business code and looping and make dynamic schemas in postgres

Now see my api, I am doing CRUD based on req.user.code(from login session),and i am finally matching showing datas according to particular schemas,

So finally i have clean separate schemas for each client

Thanks!
